import { jsPDF } from "jspdf";
import { autoTable } from "jspdf-autotable";
import { TestRun, TestResult } from "@/models/types";
import { PdfExportOptions } from "@/models/exportTypes";
import { formatDate, formatDuration, passRate } from "@/utils/format";

// Color palette
const COLORS = {
  primary: [37, 99, 235] as [number, number, number],      // blue
  success: [34, 139, 94] as [number, number, number],       // green
  destructive: [220, 53, 69] as [number, number, number],   // red
  warning: [234, 170, 0] as [number, number, number],       // amber
  muted: [128, 138, 155] as [number, number, number],       // gray
  dark: [30, 41, 59] as [number, number, number],           // dark
  light: [248, 250, 252] as [number, number, number],       // light bg
  white: [255, 255, 255] as [number, number, number],
};

function gray(c: [number, number, number]): [number, number, number] {
  const g = Math.round(c[0] * 0.299 + c[1] * 0.587 + c[2] * 0.114);
  return [g, g, g];
}

function col(c: [number, number, number], mode: "color" | "grayscale"): [number, number, number] {
  return mode === "grayscale" ? gray(c) : c;
}

function statusColor(status: string, mode: "color" | "grayscale"): [number, number, number] {
  if (status === "passed") return col(COLORS.success, mode);
  if (status === "failed") return col(COLORS.destructive, mode);
  return col(COLORS.muted, mode);
}

export function generatePdfReport(run: TestRun, options: PdfExportOptions): void {
  const rawM = run.manifest;
  const ov = options.metadataOverrides;
  const m = {
    ...rawM,
    runId: ov.runId || rawM.runId,
    branch: ov.branch || rawM.branch,
    environment: ov.environment || rawM.environment,
    timestamp: ov.timestamp || rawM.timestamp,
  };
  const rate = passRate(m);
  const cm = options.colorMode;
  const pageFormat = options.pageSize === "letter" ? "letter" : "a4";

  const doc = new jsPDF({ orientation: "portrait", unit: "mm", format: pageFormat });
  const pageWidth = doc.internal.pageSize.getWidth();
  const pageHeight = doc.internal.pageSize.getHeight();
  const margin = 15;
  const contentWidth = pageWidth - margin * 2;
  let y = margin;

  // Helpers
  const addPageFooter = () => {
    const pageCount = doc.getNumberOfPages();
    for (let i = 1; i <= pageCount; i++) {
      doc.setPage(i);
      doc.setFontSize(8);
      doc.setTextColor(...col(COLORS.muted, cm));
      doc.text(`Page ${i} of ${pageCount}`, pageWidth / 2, pageHeight - 8, { align: "center" });
      if (options.footerNote) {
        doc.text(options.footerNote, margin, pageHeight - 8);
      }
      doc.text(`Generated ${new Date().toLocaleDateString()}`, pageWidth - margin, pageHeight - 8, { align: "right" });
    }
  };

  const checkPageBreak = (needed: number) => {
    if (y + needed > pageHeight - 20) {
      doc.addPage();
      y = margin;
    }
  };

  const drawSectionHeader = (title: string) => {
    checkPageBreak(12);
    doc.setFontSize(12);
    doc.setFont("helvetica", "bold");
    doc.setTextColor(...col(COLORS.dark, cm));
    doc.text(title, margin, y);
    y += 2;
    doc.setDrawColor(...col(COLORS.primary, cm));
    doc.setLineWidth(0.5);
    doc.line(margin, y, margin + contentWidth, y);
    y += 6;
  };

  // ===== HEADER =====
  // Logo box
  doc.setFillColor(...col(COLORS.primary, cm));
  doc.roundedRect(margin, y, 14, 14, 2, 2, "F");
  doc.setFontSize(10);
  doc.setFont("helvetica", "bold");
  doc.setTextColor(...COLORS.white);
  doc.text(options.logoText, margin + 7, y + 9, { align: "center" });

  // Title
  doc.setFontSize(18);
  doc.setTextColor(...col(COLORS.dark, cm));
  doc.text(options.reportTitle, margin + 18, y + 6);

  if (options.subtitle) {
    doc.setFontSize(10);
    doc.setTextColor(...col(COLORS.muted, cm));
    doc.text(options.subtitle, margin + 18, y + 12);
  }

  y += 20;

  // Organization / Project line
  if (options.organizationName || options.projectName) {
    doc.setFontSize(9);
    doc.setTextColor(...col(COLORS.muted, cm));
    const parts = [options.organizationName, options.projectName].filter(Boolean).join(" · ");
    doc.text(parts, margin, y);
    y += 5;
  }

  if (options.generatedBy) {
    doc.setFontSize(9);
    doc.setTextColor(...col(COLORS.muted, cm));
    doc.text(`Generated by: ${options.generatedBy}`, margin, y);
    y += 5;
  }

  // Header divider
  doc.setDrawColor(...col(COLORS.primary, cm));
  doc.setLineWidth(1);
  doc.line(margin, y, margin + contentWidth, y);
  y += 8;

  // Header note
  if (options.headerNote) {
    doc.setFontSize(9);
    doc.setFont("helvetica", "italic");
    doc.setTextColor(...col(COLORS.muted, cm));
    const lines = doc.splitTextToSize(options.headerNote, contentWidth);
    doc.text(lines, margin, y);
    y += lines.length * 4.5 + 4;
  }

  // ===== EXECUTIVE SUMMARY =====
  if (options.executiveSummary) {
    drawSectionHeader("Executive Summary");
    doc.setFontSize(9);
    doc.setFont("helvetica", "normal");
    doc.setTextColor(...col(COLORS.dark, cm));
    const lines = doc.splitTextToSize(options.executiveSummary, contentWidth);
    doc.text(lines, margin, y);
    y += lines.length * 4.5 + 6;
  }

  // ===== METADATA =====
  if (options.includeMetadata) {
    drawSectionHeader("Run Metadata");
    const metaRows: string[][] = [
      ["Run ID", m.runId],
      ["Timestamp", formatDate(m.timestamp)],
      ["Branch", m.branch],
      ["Environment", m.environment],
      ["Duration", formatDuration(m.duration)],
    ];
    // Custom variables
    for (const cv of options.customVariables) {
      if (cv.key && cv.value) metaRows.push([cv.key, cv.value]);
    }

    autoTable(doc, {
      startY: y,
      head: [],
      body: metaRows,
      theme: "plain",
      margin: { left: margin, right: margin },
      styles: { fontSize: 9, cellPadding: 2, textColor: col(COLORS.dark, cm) },
      columnStyles: {
        0: { fontStyle: "bold", cellWidth: 40, textColor: col(COLORS.muted, cm) },
      },
    });
    y = (doc as any).lastAutoTable.finalY + 8;
  }

  // ===== SUMMARY STATS =====
  if (options.includeSummaryStats) {
    drawSectionHeader("Summary");

    // Stats boxes
    const stats = [
      { label: "Total", value: String(m.total), color: col(COLORS.dark, cm) },
      { label: "Passed", value: String(m.passed), color: col(COLORS.success, cm) },
      { label: "Failed", value: String(m.failed), color: col(COLORS.destructive, cm) },
      { label: "Skipped", value: String(m.skipped), color: col(COLORS.muted, cm) },
      { label: "Pass Rate", value: `${rate}%`, color: rate >= 95 ? col(COLORS.success, cm) : rate >= 80 ? col(COLORS.warning, cm) : col(COLORS.destructive, cm) },
    ];

    const boxWidth = contentWidth / stats.length - 2;
    stats.forEach((s, i) => {
      const x = margin + i * (boxWidth + 2);
      doc.setFillColor(...col(COLORS.light, cm));
      doc.roundedRect(x, y, boxWidth, 18, 1.5, 1.5, "F");

      doc.setFontSize(7);
      doc.setFont("helvetica", "normal");
      doc.setTextColor(...col(COLORS.muted, cm));
      doc.text(s.label.toUpperCase(), x + boxWidth / 2, y + 6, { align: "center" });

      doc.setFontSize(14);
      doc.setFont("helvetica", "bold");
      doc.setTextColor(...s.color);
      doc.text(s.value, x + boxWidth / 2, y + 14, { align: "center" });
    });
    y += 24;
  }

  // ===== PASS/FAIL BREAKDOWN =====
  if (options.includePassFailBreakdown) {
    checkPageBreak(20);
    // Progress bar
    const barHeight = 6;
    const passWidth = (m.passed / m.total) * contentWidth;
    const failWidth = (m.failed / m.total) * contentWidth;

    doc.setFillColor(...col(COLORS.success, cm));
    doc.roundedRect(margin, y, passWidth, barHeight, 1, 1, "F");
    doc.setFillColor(...col(COLORS.destructive, cm));
    doc.rect(margin + passWidth, y, failWidth, barHeight, "F");
    doc.setFillColor(...col(COLORS.muted, cm));
    doc.roundedRect(margin + passWidth + failWidth, y, contentWidth - passWidth - failWidth, barHeight, 1, 1, "F");

    y += barHeight + 3;
    doc.setFontSize(7);
    doc.setFont("helvetica", "normal");
    doc.setTextColor(...col(COLORS.success, cm));
    doc.text(`${m.passed} passed`, margin, y);
    doc.setTextColor(...col(COLORS.destructive, cm));
    doc.text(`${m.failed} failed`, margin + contentWidth / 2, y, { align: "center" });
    doc.setTextColor(...col(COLORS.muted, cm));
    doc.text(`${m.skipped} skipped`, margin + contentWidth, y, { align: "right" });
    y += 8;
  }

  // ===== TAG SUMMARY =====
  if (options.includeTagSummary) {
    const tagMap = new Map<string, { total: number; passed: number; failed: number }>();
    for (const t of run.results) {
      for (const tag of t.tags) {
        const e = tagMap.get(tag) || { total: 0, passed: 0, failed: 0 };
        e.total++;
        if (t.status === "passed") e.passed++;
        if (t.status === "failed") e.failed++;
        tagMap.set(tag, e);
      }
    }
    if (tagMap.size > 0) {
      drawSectionHeader("Tag Summary");
      const tagRows = [...tagMap.entries()].map(([tag, s]) => [
        tag,
        String(s.total),
        String(s.passed),
        String(s.failed),
        `${Math.round((s.passed / s.total) * 100)}%`,
      ]);
      autoTable(doc, {
        startY: y,
        head: [["Tag", "Total", "Passed", "Failed", "Pass Rate"]],
        body: tagRows,
        theme: "grid",
        margin: { left: margin, right: margin },
        headStyles: { fillColor: col(COLORS.primary, cm), fontSize: 8, fontStyle: "bold" },
        styles: { fontSize: 8, cellPadding: 2 },
        alternateRowStyles: { fillColor: col(COLORS.light, cm) },
      });
      y = (doc as any).lastAutoTable.finalY + 8;
    }
  }

  // ===== SUITE BREAKDOWN =====
  if (options.includeSuiteBreakdown) {
    const suiteMap = new Map<string, { total: number; passed: number; failed: number; skipped: number; duration: number }>();
    for (const t of run.results) {
      const e = suiteMap.get(t.suite) || { total: 0, passed: 0, failed: 0, skipped: 0, duration: 0 };
      e.total++;
      if (t.status === "passed") e.passed++;
      if (t.status === "failed") e.failed++;
      if (t.status === "skipped") e.skipped++;
      e.duration += t.duration;
      suiteMap.set(t.suite, e);
    }
    if (suiteMap.size > 0) {
      drawSectionHeader("Suite Breakdown");
      const suiteRows = [...suiteMap.entries()].map(([suite, s]) => [
        suite,
        String(s.total),
        String(s.passed),
        String(s.failed),
        String(s.skipped),
        `${Math.round((s.passed / s.total) * 100)}%`,
        `${Math.round(s.duration / s.total)}ms avg`,
      ]);
      autoTable(doc, {
        startY: y,
        head: [["Suite", "Total", "Passed", "Failed", "Skipped", "Rate", "Avg Duration"]],
        body: suiteRows,
        theme: "grid",
        margin: { left: margin, right: margin },
        headStyles: { fillColor: col(COLORS.primary, cm), fontSize: 8, fontStyle: "bold" },
        styles: { fontSize: 8, cellPadding: 2 },
        alternateRowStyles: { fillColor: col(COLORS.light, cm) },
      });
      y = (doc as any).lastAutoTable.finalY + 8;
    }
  }

  // ===== DURATION ANALYSIS =====
  if (options.includeDurationAnalysis) {
    drawSectionHeader("Duration Analysis");
    const sorted = [...run.results].sort((a, b) => b.duration - a.duration);
    const top5 = sorted.slice(0, 5);
    const avgDuration = Math.round(run.results.reduce((s, t) => s + t.duration, 0) / run.results.length);
    const maxDuration = sorted[0]?.duration || 0;
    const minDuration = sorted[sorted.length - 1]?.duration || 0;

    doc.setFontSize(9);
    doc.setFont("helvetica", "normal");
    doc.setTextColor(...col(COLORS.dark, cm));
    doc.text(`Average: ${avgDuration}ms  |  Max: ${maxDuration}ms  |  Min: ${minDuration}ms`, margin, y);
    y += 6;

    autoTable(doc, {
      startY: y,
      head: [["#", "Test Name", "Duration", "Status"]],
      body: top5.map((t, i) => [
        String(i + 1),
        t.name,
        `${t.duration}ms`,
        t.status.toUpperCase(),
      ]),
      theme: "grid",
      margin: { left: margin, right: margin },
      headStyles: { fillColor: col(COLORS.warning, cm), fontSize: 8, fontStyle: "bold", textColor: col(COLORS.dark, cm) },
      styles: { fontSize: 8, cellPadding: 2 },
      columnStyles: { 1: { cellWidth: "auto" } },
      alternateRowStyles: { fillColor: col(COLORS.light, cm) },
      didParseCell: (data: any) => {
        if (data.column.index === 3 && data.section === "body") {
          const status = data.cell.raw as string;
          if (status === "PASSED") data.cell.styles.textColor = col(COLORS.success, cm);
          else if (status === "FAILED") data.cell.styles.textColor = col(COLORS.destructive, cm);
          else data.cell.styles.textColor = col(COLORS.muted, cm);
        }
      },
    });
    y = (doc as any).lastAutoTable.finalY + 8;
  }

  // ===== TEST LIST =====
  if (options.includeTestList) {
    let tests: TestResult[] = run.results;
    if (options.includeFailedOnly) {
      tests = tests.filter((t) => t.status === "failed");
    }
    if (!options.includeSkippedTests) {
      tests = tests.filter((t) => t.status !== "skipped");
    }

    const sectionTitle = options.includeFailedOnly ? "Failed Tests" : "Test Results";
    drawSectionHeader(`${sectionTitle} (${tests.length})`);

    const testRows: (string | { content: string; styles?: any })[][] = [];
    for (const t of tests) {
      const row: (string | { content: string; styles?: any })[] = [
        { content: t.status.toUpperCase(), styles: { textColor: statusColor(t.status, cm), fontStyle: "bold" } },
        t.name,
        `${t.duration}ms`,
        t.retries > 0 ? String(t.retries) : "-",
      ];
      testRows.push(row);

      // Error details sub-row
      if (options.includeErrorDetails && t.error) {
        testRows.push([
          { content: "", styles: {} },
          { content: `ERROR: ${t.error.split("\n")[0]}`, styles: { textColor: col(COLORS.destructive, cm), fontSize: 7, fontStyle: "italic" } },
          "",
          "",
        ]);
      }

      // Logs sub-row
      if (options.includeLogs && t.logs && t.logs.length > 0) {
        testRows.push([
          { content: "", styles: {} },
          { content: `LOGS: ${t.logs.join(" | ")}`, styles: { textColor: col(COLORS.muted, cm), fontSize: 7, fontStyle: "italic" } },
          "",
          "",
        ]);
      }
    }

    autoTable(doc, {
      startY: y,
      head: [["Status", "Test Name", "Duration", "Retries"]],
      body: testRows,
      theme: "grid",
      margin: { left: margin, right: margin },
      headStyles: { fillColor: col(COLORS.primary, cm), fontSize: 8, fontStyle: "bold" },
      styles: { fontSize: 8, cellPadding: 2, overflow: "linebreak" },
      columnStyles: {
        0: { cellWidth: 18, halign: "center" },
        1: { cellWidth: "auto" },
        2: { cellWidth: 22, halign: "right" },
        3: { cellWidth: 16, halign: "center" },
      },
      alternateRowStyles: { fillColor: col(COLORS.light, cm) },
    });
    y = (doc as any).lastAutoTable.finalY + 8;
  }

  // Footer
  addPageFooter();

  // Save
  const safeName = options.fileName.replace(/[^a-zA-Z0-9-_]/g, "_");
  doc.save(`${safeName}.pdf`);
}
