import { jsPDF } from "jspdf";
import { autoTable } from "jspdf-autotable";
import { SuiteExportOptions } from "@/models/suiteExportTypes";
import { SuiteReportData } from "@/services/suiteReportData";
import { formatDate } from "@/utils/format";

const COLORS = {
  primary: [37, 99, 235] as [number, number, number],
  success: [34, 139, 94] as [number, number, number],
  destructive: [220, 53, 69] as [number, number, number],
  warning: [234, 170, 0] as [number, number, number],
  muted: [128, 138, 155] as [number, number, number],
  dark: [30, 41, 59] as [number, number, number],
  light: [248, 250, 252] as [number, number, number],
  white: [255, 255, 255] as [number, number, number],
};

function gray(c: [number, number, number]): [number, number, number] {
  const g = Math.round(c[0] * 0.299 + c[1] * 0.587 + c[2] * 0.114);
  return [g, g, g];
}

function col(c: [number, number, number], mode: "color" | "grayscale"): [number, number, number] {
  return mode === "grayscale" ? gray(c) : c;
}

function statusColor(status: string, mode: "color" | "grayscale"): [number, number, number] {
  if (status === "passed") return col(COLORS.success, mode);
  if (status === "failed") return col(COLORS.destructive, mode);
  return col(COLORS.muted, mode);
}

function rateColor(rate: number, mode: "color" | "grayscale"): [number, number, number] {
  if (rate >= 95) return col(COLORS.success, mode);
  if (rate >= 80) return col(COLORS.warning, mode);
  return col(COLORS.destructive, mode);
}

export function generateSuitePdfReport(data: SuiteReportData, options: SuiteExportOptions): void {
  const cm = options.colorMode;
  const pageFormat = options.pageSize === "letter" ? "letter" : "a4";
  const displayName = options.metadataOverrides.suiteName || data.suiteName;

  const doc = new jsPDF({ orientation: "portrait", unit: "mm", format: pageFormat });
  const pageWidth = doc.internal.pageSize.getWidth();
  const pageHeight = doc.internal.pageSize.getHeight();
  const margin = 15;
  const contentWidth = pageWidth - margin * 2;
  let y = margin;

  const addPageFooter = () => {
    const pageCount = doc.getNumberOfPages();
    for (let i = 1; i <= pageCount; i++) {
      doc.setPage(i);
      doc.setFontSize(8);
      doc.setTextColor(...col(COLORS.muted, cm));
      doc.text(`Page ${i} of ${pageCount}`, pageWidth / 2, pageHeight - 8, { align: "center" });
      if (options.footerNote) doc.text(options.footerNote, margin, pageHeight - 8);
      doc.text(`Generated ${new Date().toLocaleDateString()}`, pageWidth - margin, pageHeight - 8, { align: "right" });
    }
  };

  const checkPageBreak = (needed: number) => {
    if (y + needed > pageHeight - 20) { doc.addPage(); y = margin; }
  };

  const drawSectionHeader = (title: string) => {
    checkPageBreak(12);
    doc.setFontSize(12);
    doc.setFont("helvetica", "bold");
    doc.setTextColor(...col(COLORS.dark, cm));
    doc.text(title, margin, y);
    y += 2;
    doc.setDrawColor(...col(COLORS.primary, cm));
    doc.setLineWidth(0.5);
    doc.line(margin, y, margin + contentWidth, y);
    y += 6;
  };

  // ===== HEADER =====
  doc.setFillColor(...col(COLORS.primary, cm));
  doc.roundedRect(margin, y, 14, 14, 2, 2, "F");
  doc.setFontSize(10);
  doc.setFont("helvetica", "bold");
  doc.setTextColor(...COLORS.white);
  doc.text(options.logoText, margin + 7, y + 9, { align: "center" });

  doc.setFontSize(18);
  doc.setTextColor(...col(COLORS.dark, cm));
  doc.text(options.reportTitle, margin + 18, y + 6);

  if (options.subtitle) {
    doc.setFontSize(10);
    doc.setTextColor(...col(COLORS.muted, cm));
    doc.text(options.subtitle, margin + 18, y + 12);
  }
  y += 20;

  if (options.organizationName || options.projectName) {
    doc.setFontSize(9);
    doc.setTextColor(...col(COLORS.muted, cm));
    doc.text([options.organizationName, options.projectName].filter(Boolean).join(" · "), margin, y);
    y += 5;
  }
  if (options.generatedBy) {
    doc.setFontSize(9);
    doc.setTextColor(...col(COLORS.muted, cm));
    doc.text(`Generated by: ${options.generatedBy}`, margin, y);
    y += 5;
  }

  doc.setDrawColor(...col(COLORS.primary, cm));
  doc.setLineWidth(1);
  doc.line(margin, y, margin + contentWidth, y);
  y += 8;

  if (options.headerNote) {
    doc.setFontSize(9);
    doc.setFont("helvetica", "italic");
    doc.setTextColor(...col(COLORS.muted, cm));
    const lines = doc.splitTextToSize(options.headerNote, contentWidth);
    doc.text(lines, margin, y);
    y += lines.length * 4.5 + 4;
  }

  // ===== EXECUTIVE SUMMARY =====
  if (options.executiveSummary) {
    drawSectionHeader("Executive Summary");
    doc.setFontSize(9);
    doc.setFont("helvetica", "normal");
    doc.setTextColor(...col(COLORS.dark, cm));
    const lines = doc.splitTextToSize(options.executiveSummary, contentWidth);
    doc.text(lines, margin, y);
    y += lines.length * 4.5 + 6;
  }

  // ===== SUITE METADATA =====
  if (options.includeMetadata) {
    drawSectionHeader("Suite Overview");
    const metaRows: string[][] = [
      ["Suite Name", displayName],
      ["First Seen", formatDate(data.firstSeen)],
      ["Last Seen", formatDate(data.lastSeen)],
      ["Runs Analyzed", `${data.runsAnalyzed} of ${data.totalRuns} total`],
    ];
    if (options.metadataOverrides.environment) metaRows.push(["Environment", options.metadataOverrides.environment]);
    for (const cv of options.customVariables) {
      if (cv.key && cv.value) metaRows.push([cv.key, cv.value]);
    }
    autoTable(doc, {
      startY: y, head: [], body: metaRows, theme: "plain",
      margin: { left: margin, right: margin },
      styles: { fontSize: 9, cellPadding: 2, textColor: col(COLORS.dark, cm) },
      columnStyles: { 0: { fontStyle: "bold", cellWidth: 40, textColor: col(COLORS.muted, cm) } },
    });
    y = (doc as any).lastAutoTable.finalY + 8;
  }

  // ===== STABILITY OVERVIEW =====
  if (options.includeStabilityOverview) {
    drawSectionHeader("Stability Overview");
    const stats = [
      { label: "Stability", value: `${data.stabilityScore}%`, color: rateColor(data.stabilityScore, cm) },
      { label: "Avg Pass Rate", value: `${data.avgPassRate}%`, color: rateColor(data.avgPassRate, cm) },
      { label: "Perfect Runs", value: `${data.perfectRuns}/${data.runsAnalyzed}`, color: col(COLORS.dark, cm) },
      { label: "Trend", value: `${data.trend >= 0 ? "+" : ""}${data.trend}%`, color: data.trend >= 0 ? col(COLORS.success, cm) : col(COLORS.destructive, cm) },
    ];

    const boxWidth = contentWidth / stats.length - 2;
    stats.forEach((s, i) => {
      const x = margin + i * (boxWidth + 2);
      doc.setFillColor(...col(COLORS.light, cm));
      doc.roundedRect(x, y, boxWidth, 18, 1.5, 1.5, "F");
      doc.setFontSize(7);
      doc.setFont("helvetica", "normal");
      doc.setTextColor(...col(COLORS.muted, cm));
      doc.text(s.label.toUpperCase(), x + boxWidth / 2, y + 6, { align: "center" });
      doc.setFontSize(14);
      doc.setFont("helvetica", "bold");
      doc.setTextColor(...s.color);
      doc.text(s.value, x + boxWidth / 2, y + 14, { align: "center" });
    });
    y += 24;

    // Stability bar
    if (data.history.length > 0) {
      const barWidth = contentWidth / data.history.length;
      data.history.forEach((h, i) => {
        const c = h.passRate === 100 ? col(COLORS.success, cm) : h.passRate >= 80 ? col(COLORS.warning, cm) : col(COLORS.destructive, cm);
        doc.setFillColor(...c);
        doc.rect(margin + i * barWidth, y, barWidth - 0.5, 4, "F");
      });
      y += 6;
      doc.setFontSize(7);
      doc.setTextColor(...col(COLORS.muted, cm));
      doc.text("Each block = 1 run", margin + contentWidth / 2, y, { align: "center" });
      y += 6;
    }
  }

  // ===== PASS RATE TREND =====
  if (options.includePassRateTrend && data.history.length > 1) {
    drawSectionHeader("Pass Rate Trend");
    const recentHistory = [...data.history].reverse().slice(0, 10);
    autoTable(doc, {
      startY: y,
      head: [["Run", "Date", "Tests", "✓", "✗", "Rate", "Duration"]],
      body: recentHistory.map((h) => [
        h.runId.slice(0, 16),
        new Date(h.timestamp).toLocaleDateString("en-US", { month: "short", day: "numeric" }),
        String(h.total),
        String(h.passed),
        String(h.failed),
        `${h.passRate}%`,
        `${Math.round(h.duration / 1000)}s`,
      ]),
      theme: "grid",
      margin: { left: margin, right: margin },
      headStyles: { fillColor: col(COLORS.primary, cm), fontSize: 8, fontStyle: "bold" },
      styles: { fontSize: 8, cellPadding: 2 },
      alternateRowStyles: { fillColor: col(COLORS.light, cm) },
      didParseCell: (cellData: any) => {
        if (cellData.column.index === 5 && cellData.section === "body") {
          const rate = parseInt(cellData.cell.raw as string);
          cellData.cell.styles.textColor = rateColor(rate, cm);
          cellData.cell.styles.fontStyle = "bold";
        }
      },
    });
    y = (doc as any).lastAutoTable.finalY + 8;
  }

  // ===== CROSS-RUN COMPARISON =====
  if (options.includeCrossRunComparison && data.history.length > 1) {
    drawSectionHeader("Cross-Run Test Comparison");
    const recentRuns = [...data.history].reverse().slice(0, 5);
    const testNames = [...data.crossRunStatus.keys()].sort();
    const displayTests = testNames.slice(0, 20);

    const head = ["Test", ...recentRuns.map((h) => new Date(h.timestamp).toLocaleDateString("en-US", { month: "short", day: "numeric" }))];
    const body = displayTests.map((name) => {
      const runMap = data.crossRunStatus.get(name)!;
      return [
        name.length > 30 ? name.slice(0, 28) + "…" : name,
        ...recentRuns.map((h) => {
          const s = runMap.get(h.runId);
          return s === "passed" ? "PASS" : s === "failed" ? "FAIL" : s === "skipped" ? "SKIP" : "—";
        }),
      ];
    });

    autoTable(doc, {
      startY: y,
      head: [head],
      body,
      theme: "grid",
      margin: { left: margin, right: margin },
      headStyles: { fillColor: col(COLORS.primary, cm), fontSize: 7, fontStyle: "bold" },
      styles: { fontSize: 7, cellPadding: 1.5, halign: "center" },
      columnStyles: { 0: { halign: "left", cellWidth: "auto" } },
      alternateRowStyles: { fillColor: col(COLORS.light, cm) },
      didParseCell: (cellData: any) => {
        if (cellData.column.index > 0 && cellData.section === "body") {
          const val = cellData.cell.raw as string;
          if (val === "PASS") cellData.cell.styles.textColor = col(COLORS.success, cm);
          else if (val === "FAIL") cellData.cell.styles.textColor = col(COLORS.destructive, cm);
          else cellData.cell.styles.textColor = col(COLORS.muted, cm);
          cellData.cell.styles.fontStyle = "bold";
        }
      },
    });
    y = (doc as any).lastAutoTable.finalY + 4;
    if (testNames.length > 20) {
      doc.setFontSize(7);
      doc.setTextColor(...col(COLORS.muted, cm));
      doc.text(`Showing 20 of ${testNames.length} tests`, margin + contentWidth / 2, y, { align: "center" });
      y += 4;
    }
    y += 4;
  }

  // ===== FLAKY TESTS =====
  if (options.includeFlakyTests && data.flakyTests.length > 0) {
    drawSectionHeader(`Flaky Tests (${data.flakyTests.length})`);
    autoTable(doc, {
      startY: y,
      head: [["Test Name", "Runs", "Passed", "Failed", "Flake Rate", "Last"]],
      body: data.flakyTests.map((t) => [
        t.name.length > 35 ? t.name.slice(0, 33) + "…" : t.name,
        String(t.totalRuns),
        String(t.passed),
        String(t.failed),
        `${t.flakeRate}%`,
        t.lastStatus.toUpperCase(),
      ]),
      theme: "grid",
      margin: { left: margin, right: margin },
      headStyles: { fillColor: col(COLORS.warning, cm), fontSize: 8, fontStyle: "bold", textColor: col(COLORS.dark, cm) },
      styles: { fontSize: 8, cellPadding: 2 },
      alternateRowStyles: { fillColor: col(COLORS.light, cm) },
      didParseCell: (cellData: any) => {
        if (cellData.column.index === 5 && cellData.section === "body") {
          const status = (cellData.cell.raw as string).toLowerCase();
          cellData.cell.styles.textColor = statusColor(status, cm);
          cellData.cell.styles.fontStyle = "bold";
        }
      },
    });
    y = (doc as any).lastAutoTable.finalY + 8;
  }

  // ===== FAILURE PATTERNS =====
  if (options.includeFailurePatterns && data.failurePatterns.length > 0) {
    drawSectionHeader("Failure Patterns");
    for (const p of data.failurePatterns) {
      checkPageBreak(20);
      doc.setFontSize(10);
      doc.setFont("helvetica", "bold");
      doc.setTextColor(...col(COLORS.dark, cm));
      doc.text(`${p.category} — ${p.count} occurrences (${p.percentage}%)`, margin, y);
      y += 4;

      // Bar
      const barW = (p.percentage / 100) * contentWidth;
      doc.setFillColor(...col(COLORS.light, cm));
      doc.roundedRect(margin, y, contentWidth, 3, 1, 1, "F");
      doc.setFillColor(...col(COLORS.destructive, cm));
      doc.roundedRect(margin, y, barW, 3, 1, 1, "F");
      y += 5;

      if (p.sampleError) {
        doc.setFontSize(7);
        doc.setFont("helvetica", "italic");
        doc.setTextColor(...col(COLORS.muted, cm));
        const sample = p.sampleError.length > 80 ? p.sampleError.slice(0, 78) + "…" : p.sampleError;
        doc.text(`Sample: ${sample}`, margin, y);
        y += 4;
      }

      doc.setFontSize(7);
      doc.setFont("helvetica", "normal");
      doc.setTextColor(...col(COLORS.muted, cm));
      const affected = p.affectedTests.slice(0, 3).join(", ") + (p.affectedTests.length > 3 ? ` +${p.affectedTests.length - 3} more` : "");
      doc.text(`Affects: ${affected}`, margin, y);
      y += 6;
    }
    y += 2;
  }

  // ===== TAG SUMMARY =====
  if (options.includeTagSummary && data.tagMap.size > 0) {
    drawSectionHeader("Tag Summary (Latest Run)");
    const tagRows = [...data.tagMap.entries()].map(([tag, s]) => [
      tag, String(s.total), String(s.passed), String(s.failed), `${Math.round((s.passed / s.total) * 100)}%`,
    ]);
    autoTable(doc, {
      startY: y,
      head: [["Tag", "Total", "Passed", "Failed", "Pass Rate"]],
      body: tagRows,
      theme: "grid",
      margin: { left: margin, right: margin },
      headStyles: { fillColor: col(COLORS.primary, cm), fontSize: 8, fontStyle: "bold" },
      styles: { fontSize: 8, cellPadding: 2 },
      alternateRowStyles: { fillColor: col(COLORS.light, cm) },
    });
    y = (doc as any).lastAutoTable.finalY + 8;
  }

  // ===== DURATION ANALYSIS =====
  if (options.includeDurationAnalysis && data.latestResults.length > 0) {
    drawSectionHeader("Duration Analysis (Latest Run)");
    const sorted = [...data.latestResults].sort((a, b) => b.duration - a.duration);
    const avg = Math.round(sorted.reduce((s, t) => s + t.duration, 0) / sorted.length);

    doc.setFontSize(9);
    doc.setFont("helvetica", "normal");
    doc.setTextColor(...col(COLORS.dark, cm));
    doc.text(`Average: ${avg}ms  |  Max: ${sorted[0]?.duration || 0}ms  |  Min: ${sorted[sorted.length - 1]?.duration || 0}ms`, margin, y);
    y += 6;

    autoTable(doc, {
      startY: y,
      head: [["#", "Test Name", "Duration", "Status"]],
      body: sorted.slice(0, 5).map((t, i) => [String(i + 1), t.name, `${t.duration}ms`, t.status.toUpperCase()]),
      theme: "grid",
      margin: { left: margin, right: margin },
      headStyles: { fillColor: col(COLORS.warning, cm), fontSize: 8, fontStyle: "bold", textColor: col(COLORS.dark, cm) },
      styles: { fontSize: 8, cellPadding: 2 },
      alternateRowStyles: { fillColor: col(COLORS.light, cm) },
      didParseCell: (cellData: any) => {
        if (cellData.column.index === 3 && cellData.section === "body") {
          const status = (cellData.cell.raw as string).toLowerCase();
          cellData.cell.styles.textColor = statusColor(status, cm);
        }
      },
    });
    y = (doc as any).lastAutoTable.finalY + 8;
  }

  // ===== TEST LIST =====
  if (options.includeTestList) {
    let tests = data.latestResults;
    if (options.includeFailedOnly) tests = tests.filter((t) => t.status === "failed");
    if (!options.includeSkippedTests) tests = tests.filter((t) => t.status !== "skipped");

    const title = options.includeFailedOnly ? "Failed Tests" : "Test Results";
    drawSectionHeader(`${title} — Latest Run (${tests.length})`);

    const testRows: (string | { content: string; styles?: any })[][] = [];
    for (const t of tests) {
      testRows.push([
        { content: t.status.toUpperCase(), styles: { textColor: statusColor(t.status, cm), fontStyle: "bold" } },
        t.name,
        `${t.duration}ms`,
        t.retries > 0 ? String(t.retries) : "-",
      ]);
      if (options.includeErrorDetails && t.error) {
        testRows.push([
          { content: "", styles: {} },
          { content: `ERROR: ${t.error.split("\n")[0]}`, styles: { textColor: col(COLORS.destructive, cm), fontSize: 7, fontStyle: "italic" } },
          "", "",
        ]);
      }
    }

    autoTable(doc, {
      startY: y,
      head: [["Status", "Test Name", "Duration", "Retries"]],
      body: testRows,
      theme: "grid",
      margin: { left: margin, right: margin },
      headStyles: { fillColor: col(COLORS.primary, cm), fontSize: 8, fontStyle: "bold" },
      styles: { fontSize: 8, cellPadding: 2, overflow: "linebreak" },
      columnStyles: { 0: { cellWidth: 18, halign: "center" }, 1: { cellWidth: "auto" }, 2: { cellWidth: 22, halign: "right" }, 3: { cellWidth: 16, halign: "center" } },
      alternateRowStyles: { fillColor: col(COLORS.light, cm) },
    });
  }

  addPageFooter();
  const safeName = options.fileName.replace(/[^a-zA-Z0-9-_]/g, "_");
  doc.save(`${safeName}.pdf`);
}
