import { useState } from "react";
import { TestRun } from "@/models/types";
import { PdfExportOptions, defaultExportOptions } from "@/models/exportTypes";
import { generatePdfReport } from "@/services/pdfGenerator";
import { Dialog, DialogContent, DialogHeader, DialogTitle, DialogTrigger } from "@/components/ui/dialog";
import { Button } from "@/components/ui/button";
import { Input } from "@/components/ui/input";
import { Label } from "@/components/ui/label";
import { Textarea } from "@/components/ui/textarea";
import { Switch } from "@/components/ui/switch";
import { Separator } from "@/components/ui/separator";

interface ExportDialogProps {
  run: TestRun;
}

export function ExportDialog({ run }: ExportDialogProps) {
  const [open, setOpen] = useState(false);
  const [options, setOptions] = useState<PdfExportOptions>(() => ({
    ...defaultExportOptions,
    fileName: `test-report-${run.manifest.runId}`,
    subtitle: `Run: ${run.manifest.runId}`,
  }));
  const [generating, setGenerating] = useState(false);

  const update = <K extends keyof PdfExportOptions>(key: K, value: PdfExportOptions[K]) => {
    setOptions((prev) => ({ ...prev, [key]: value }));
  };

  const addCustomVar = () => {
    update("customVariables", [...options.customVariables, { key: "", value: "" }]);
  };

  const updateCustomVar = (index: number, field: "key" | "value", val: string) => {
    const vars = [...options.customVariables];
    vars[index] = { ...vars[index], [field]: val };
    update("customVariables", vars);
  };

  const removeCustomVar = (index: number) => {
    update("customVariables", options.customVariables.filter((_, i) => i !== index));
  };

  const handleExport = () => {
    setGenerating(true);
    // Small delay so UI updates
    setTimeout(() => {
      try {
        generatePdfReport(run, options);
      } catch (e) {
        console.error("PDF generation failed:", e);
      }
      setGenerating(false);
    }, 100);
  };

  return (
    <Dialog open={open} onOpenChange={setOpen}>
      <DialogTrigger asChild>
        <Button variant="outline" size="sm" className="font-mono text-xs">
          📄 Export PDF
        </Button>
      </DialogTrigger>
      <DialogContent className="max-w-2xl max-h-[85vh] overflow-y-auto">
        <DialogHeader>
          <DialogTitle className="text-base font-semibold">Export PDF Report</DialogTitle>
          <p className="text-xs text-muted-foreground">Customize your report before exporting</p>
        </DialogHeader>

        <div className="space-y-6 py-2">
          {/* === NAMING & HEADER === */}
          <section className="space-y-3">
            <h3 className="text-xs font-semibold text-muted-foreground uppercase tracking-wider">Report Identity</h3>
            <div className="grid grid-cols-2 gap-3">
              <div className="space-y-1.5">
                <Label className="text-xs">File Name</Label>
                <Input className="h-8 text-xs font-mono" value={options.fileName} onChange={(e) => update("fileName", e.target.value)} />
              </div>
              <div className="space-y-1.5">
                <Label className="text-xs">Logo Text (2 chars)</Label>
                <Input className="h-8 text-xs font-mono" maxLength={2} value={options.logoText} onChange={(e) => update("logoText", e.target.value)} />
              </div>
            </div>
            <div className="space-y-1.5">
              <Label className="text-xs">Report Title</Label>
              <Input className="h-8 text-xs" value={options.reportTitle} onChange={(e) => update("reportTitle", e.target.value)} />
            </div>
            <div className="space-y-1.5">
              <Label className="text-xs">Subtitle</Label>
              <Input className="h-8 text-xs" value={options.subtitle} onChange={(e) => update("subtitle", e.target.value)} />
            </div>
            <div className="grid grid-cols-2 gap-3">
              <div className="space-y-1.5">
                <Label className="text-xs">Organization Name</Label>
                <Input className="h-8 text-xs" placeholder="Acme Corp" value={options.organizationName} onChange={(e) => update("organizationName", e.target.value)} />
              </div>
              <div className="space-y-1.5">
                <Label className="text-xs">Project Name</Label>
                <Input className="h-8 text-xs" value={options.projectName} onChange={(e) => update("projectName", e.target.value)} />
              </div>
            </div>
            <div className="space-y-1.5">
              <Label className="text-xs">Generated By</Label>
              <Input className="h-8 text-xs" placeholder="QA Team" value={options.generatedBy} onChange={(e) => update("generatedBy", e.target.value)} />
            </div>
          </section>

          <Separator />

          {/* === NOTES === */}
          <section className="space-y-3">
            <h3 className="text-xs font-semibold text-muted-foreground uppercase tracking-wider">Notes & Commentary</h3>
            <div className="space-y-1.5">
              <Label className="text-xs">Header Note</Label>
              <Textarea className="text-xs min-h-[50px]" placeholder="Note displayed below the header..." value={options.headerNote} onChange={(e) => update("headerNote", e.target.value)} />
            </div>
            <div className="space-y-1.5">
              <Label className="text-xs">Executive Summary</Label>
              <Textarea className="text-xs min-h-[60px]" placeholder="High-level summary for stakeholders..." value={options.executiveSummary} onChange={(e) => update("executiveSummary", e.target.value)} />
            </div>
            <div className="space-y-1.5">
              <Label className="text-xs">Footer Note</Label>
              <Input className="h-8 text-xs" placeholder="Confidential — Internal Use Only" value={options.footerNote} onChange={(e) => update("footerNote", e.target.value)} />
            </div>
          </section>

          <Separator />

          {/* === CUSTOM VARIABLES === */}
          <section className="space-y-3">
            <div className="flex items-center justify-between">
              <h3 className="text-xs font-semibold text-muted-foreground uppercase tracking-wider">Custom Variables</h3>
              <Button variant="outline" size="sm" className="h-6 text-[10px] px-2" onClick={addCustomVar}>+ Add</Button>
            </div>
            <p className="text-[10px] text-muted-foreground">Add key-value pairs to the metadata section (e.g., Sprint, Jira Ticket, Build #)</p>
            {options.customVariables.map((cv, i) => (
              <div key={i} className="flex gap-2 items-center">
                <Input className="h-7 text-xs flex-1" placeholder="Key" value={cv.key} onChange={(e) => updateCustomVar(i, "key", e.target.value)} />
                <Input className="h-7 text-xs flex-1" placeholder="Value" value={cv.value} onChange={(e) => updateCustomVar(i, "value", e.target.value)} />
                <Button variant="ghost" size="sm" className="h-7 w-7 p-0 text-destructive text-xs" onClick={() => removeCustomVar(i)}>✕</Button>
              </div>
            ))}
          </section>

          <Separator />

          {/* === SECTION TOGGLES === */}
          <section className="space-y-3">
            <h3 className="text-xs font-semibold text-muted-foreground uppercase tracking-wider">Included Sections</h3>
            <div className="grid grid-cols-1 sm:grid-cols-2 gap-2">
              {([
                ["includeSummaryStats", "Summary Statistics"],
                ["includePassFailBreakdown", "Pass/Fail Breakdown Bar"],
                ["includeMetadata", "Run Metadata"],
                ["includeTagSummary", "Tag Summary Table"],
                ["includeSuiteBreakdown", "Suite Breakdown"],
                ["includeDurationAnalysis", "Duration Analysis"],
                ["includeTestList", "Test Results List"],
                ["includeErrorDetails", "Error Details"],
                ["includeLogs", "Test Logs"],
              ] as [keyof PdfExportOptions, string][]).map(([key, label]) => (
                <div key={key} className="flex items-center justify-between rounded-md border px-3 py-2">
                  <Label className="text-xs cursor-pointer">{label}</Label>
                  <Switch checked={options[key] as boolean} onCheckedChange={(v) => update(key, v)} />
                </div>
              ))}
            </div>
          </section>

          <Separator />

          {/* === TEST FILTERING === */}
          <section className="space-y-3">
            <h3 className="text-xs font-semibold text-muted-foreground uppercase tracking-wider">Test List Filters</h3>
            <div className="space-y-2">
              <div className="flex items-center justify-between rounded-md border px-3 py-2">
                <Label className="text-xs">Show Only Failed Tests</Label>
                <Switch checked={options.includeFailedOnly} onCheckedChange={(v) => update("includeFailedOnly", v)} />
              </div>
              <div className="flex items-center justify-between rounded-md border px-3 py-2">
                <Label className="text-xs">Include Skipped Tests</Label>
                <Switch checked={options.includeSkippedTests} onCheckedChange={(v) => update("includeSkippedTests", v)} />
              </div>
            </div>
          </section>

          <Separator />

          {/* === FORMATTING === */}
          <section className="space-y-3">
            <h3 className="text-xs font-semibold text-muted-foreground uppercase tracking-wider">Formatting</h3>
            <div className="grid grid-cols-2 gap-3">
              <div className="space-y-1.5">
                <Label className="text-xs">Page Size</Label>
                <div className="flex gap-1">
                  {(["a4", "letter"] as const).map((size) => (
                    <Button
                      key={size}
                      variant={options.pageSize === size ? "default" : "outline"}
                      size="sm"
                      className="h-7 text-xs flex-1"
                      onClick={() => update("pageSize", size)}
                    >
                      {size.toUpperCase()}
                    </Button>
                  ))}
                </div>
              </div>
              <div className="space-y-1.5">
                <Label className="text-xs">Color Mode</Label>
                <div className="flex gap-1">
                  {(["color", "grayscale"] as const).map((mode) => (
                    <Button
                      key={mode}
                      variant={options.colorMode === mode ? "default" : "outline"}
                      size="sm"
                      className="h-7 text-xs flex-1"
                      onClick={() => update("colorMode", mode)}
                    >
                      {mode === "color" ? "🎨 Color" : "⬛ Gray"}
                    </Button>
                  ))}
                </div>
              </div>
            </div>
          </section>
        </div>

        {/* Export Button */}
        <div className="flex justify-end gap-2 pt-2 border-t">
          <Button variant="outline" size="sm" className="text-xs" onClick={() => setOpen(false)}>Cancel</Button>
          <Button size="sm" className="text-xs font-mono" onClick={handleExport} disabled={generating}>
            {generating ? "Generating…" : "📄 Download PDF"}
          </Button>
        </div>
      </DialogContent>
    </Dialog>
  );
}
