import { PdfExportOptions } from "@/models/exportTypes";
import { Button } from "@/components/ui/button";
import { Input } from "@/components/ui/input";
import { Label } from "@/components/ui/label";
import { Textarea } from "@/components/ui/textarea";
import { Switch } from "@/components/ui/switch";
import { Separator } from "@/components/ui/separator";

interface ExportSettingsPanelProps {
  options: PdfExportOptions;
  onChange: (options: PdfExportOptions) => void;
}

export function ExportSettingsPanel({ options, onChange }: ExportSettingsPanelProps) {
  const update = <K extends keyof PdfExportOptions>(key: K, value: PdfExportOptions[K]) => {
    onChange({ ...options, [key]: value });
  };

  const addCustomVar = () => update("customVariables", [...options.customVariables, { key: "", value: "" }]);

  const updateCustomVar = (index: number, field: "key" | "value", val: string) => {
    const vars = [...options.customVariables];
    vars[index] = { ...vars[index], [field]: val };
    update("customVariables", vars);
  };

  const removeCustomVar = (index: number) => {
    update("customVariables", options.customVariables.filter((_, i) => i !== index));
  };

  return (
    <div className="space-y-5">
      {/* REPORT IDENTITY */}
      <Section title="Report Identity">
        <div className="grid grid-cols-2 gap-2">
          <Field label="File Name">
            <Input className="h-8 text-xs font-mono" value={options.fileName} onChange={(e) => update("fileName", e.target.value)} />
          </Field>
          <Field label="Logo (2 chars)">
            <Input className="h-8 text-xs font-mono" maxLength={2} value={options.logoText} onChange={(e) => update("logoText", e.target.value)} />
          </Field>
        </div>
        <Field label="Report Title">
          <Input className="h-8 text-xs" value={options.reportTitle} onChange={(e) => update("reportTitle", e.target.value)} />
        </Field>
        <Field label="Subtitle">
          <Input className="h-8 text-xs" value={options.subtitle} onChange={(e) => update("subtitle", e.target.value)} />
        </Field>
        <div className="grid grid-cols-2 gap-2">
          <Field label="Organization">
            <Input className="h-8 text-xs" placeholder="Acme Corp" value={options.organizationName} onChange={(e) => update("organizationName", e.target.value)} />
          </Field>
          <Field label="Project">
            <Input className="h-8 text-xs" value={options.projectName} onChange={(e) => update("projectName", e.target.value)} />
          </Field>
        </div>
        <Field label="Generated By">
          <Input className="h-8 text-xs" placeholder="QA Team" value={options.generatedBy} onChange={(e) => update("generatedBy", e.target.value)} />
        </Field>
      </Section>

      <Separator />

      {/* NOTES */}
      <Section title="Notes & Commentary">
        <Field label="Header Note">
          <Textarea className="text-xs min-h-[44px]" placeholder="Displayed below the header..." value={options.headerNote} onChange={(e) => update("headerNote", e.target.value)} />
        </Field>
        <Field label="Executive Summary">
          <Textarea className="text-xs min-h-[56px]" placeholder="High-level summary for stakeholders..." value={options.executiveSummary} onChange={(e) => update("executiveSummary", e.target.value)} />
        </Field>
        <Field label="Footer Note">
          <Input className="h-8 text-xs" placeholder="Confidential — Internal Use Only" value={options.footerNote} onChange={(e) => update("footerNote", e.target.value)} />
        </Field>
      </Section>

      <Separator />

      {/* CUSTOM VARIABLES */}
      <Section title="Custom Variables" action={<Button variant="outline" size="sm" className="h-6 text-[10px] px-2" onClick={addCustomVar}>+ Add</Button>}>
        <p className="text-[10px] text-muted-foreground -mt-1">e.g. Sprint, Jira Ticket, Build #</p>
        {options.customVariables.map((cv, i) => (
          <div key={i} className="flex gap-1.5 items-center">
            <Input className="h-7 text-xs flex-1" placeholder="Key" value={cv.key} onChange={(e) => updateCustomVar(i, "key", e.target.value)} />
            <Input className="h-7 text-xs flex-1" placeholder="Value" value={cv.value} onChange={(e) => updateCustomVar(i, "value", e.target.value)} />
            <Button variant="ghost" size="sm" className="h-7 w-7 p-0 text-destructive text-xs shrink-0" onClick={() => removeCustomVar(i)}>✕</Button>
          </div>
        ))}
      </Section>

      <Separator />

      {/* SECTIONS */}
      <Section title="Included Sections">
        <div className="space-y-1.5">
          {([
            ["includeSummaryStats", "Summary Statistics"],
            ["includePassFailBreakdown", "Pass/Fail Bar"],
            ["includeMetadata", "Run Metadata"],
            ["includeTagSummary", "Tag Summary"],
            ["includeSuiteBreakdown", "Suite Breakdown"],
            ["includeDurationAnalysis", "Duration Analysis"],
            ["includeTestList", "Test Results List"],
            ["includeErrorDetails", "Error Details"],
            ["includeLogs", "Test Logs"],
          ] as [keyof PdfExportOptions, string][]).map(([key, label]) => (
            <div key={key} className="flex items-center justify-between rounded border px-2.5 py-1.5">
              <Label className="text-xs cursor-pointer">{label}</Label>
              <Switch checked={options[key] as boolean} onCheckedChange={(v) => update(key, v)} />
            </div>
          ))}
        </div>
      </Section>

      <Separator />

      {/* TEST FILTERS */}
      <Section title="Test List Filters">
        <div className="space-y-1.5">
          <div className="flex items-center justify-between rounded border px-2.5 py-1.5">
            <Label className="text-xs">Failed Tests Only</Label>
            <Switch checked={options.includeFailedOnly} onCheckedChange={(v) => update("includeFailedOnly", v)} />
          </div>
          <div className="flex items-center justify-between rounded border px-2.5 py-1.5">
            <Label className="text-xs">Include Skipped</Label>
            <Switch checked={options.includeSkippedTests} onCheckedChange={(v) => update("includeSkippedTests", v)} />
          </div>
        </div>
      </Section>

      <Separator />

      {/* FORMATTING */}
      <Section title="Formatting">
        <div className="grid grid-cols-2 gap-2">
          <div className="space-y-1">
            <Label className="text-[10px]">Page Size</Label>
            <div className="flex gap-1">
              {(["a4", "letter"] as const).map((s) => (
                <Button key={s} variant={options.pageSize === s ? "default" : "outline"} size="sm" className="h-7 text-xs flex-1" onClick={() => update("pageSize", s)}>
                  {s.toUpperCase()}
                </Button>
              ))}
            </div>
          </div>
          <div className="space-y-1">
            <Label className="text-[10px]">Color Mode</Label>
            <div className="flex gap-1">
              {(["color", "grayscale"] as const).map((mode) => (
                <Button key={mode} variant={options.colorMode === mode ? "default" : "outline"} size="sm" className="h-7 text-xs flex-1" onClick={() => update("colorMode", mode)}>
                  {mode === "color" ? "🎨" : "⬛"} {mode === "color" ? "Color" : "Gray"}
                </Button>
              ))}
            </div>
          </div>
        </div>
      </Section>
    </div>
  );
}

function Section({ title, children, action }: { title: string; children: React.ReactNode; action?: React.ReactNode }) {
  return (
    <div className="space-y-2">
      <div className="flex items-center justify-between">
        <h3 className="text-[10px] font-semibold text-muted-foreground uppercase tracking-wider">{title}</h3>
        {action}
      </div>
      {children}
    </div>
  );
}

function Field({ label, children }: { label: string; children: React.ReactNode }) {
  return (
    <div className="space-y-1">
      <Label className="text-[10px]">{label}</Label>
      {children}
    </div>
  );
}
