import { TestRun, TestResult } from "@/models/types";
import { PdfExportOptions } from "@/models/exportTypes";
import { formatDate, formatDuration, passRate } from "@/utils/format";

interface ReportPreviewProps {
  run: TestRun;
  options: PdfExportOptions;
}

function statusClass(status: string, cm: string) {
  if (cm === "grayscale") return "text-foreground";
  if (status === "passed") return "text-success";
  if (status === "failed") return "text-destructive";
  return "text-skipped";
}

function rateClass(rate: number, cm: string) {
  if (cm === "grayscale") return "text-foreground";
  if (rate >= 95) return "text-success";
  if (rate >= 80) return "text-warning";
  return "text-destructive";
}

export function ReportPreview({ run, options }: ReportPreviewProps) {
  const rawM = run.manifest;
  const ov = options.metadataOverrides;
  const m = {
    ...rawM,
    runId: ov.runId || rawM.runId,
    branch: ov.branch || rawM.branch,
    environment: ov.environment || rawM.environment,
    timestamp: ov.timestamp || rawM.timestamp,
  };
  const rate = passRate(m);
  const cm = options.colorMode;
  const isGray = cm === "grayscale";

  // Compute tag summary
  const tagMap = new Map<string, { total: number; passed: number; failed: number }>();
  for (const t of run.results) {
    for (const tag of t.tags) {
      const e = tagMap.get(tag) || { total: 0, passed: 0, failed: 0 };
      e.total++;
      if (t.status === "passed") e.passed++;
      if (t.status === "failed") e.failed++;
      tagMap.set(tag, e);
    }
  }

  // Suite breakdown
  const suiteMap = new Map<string, { total: number; passed: number; failed: number; skipped: number; duration: number }>();
  for (const t of run.results) {
    const e = suiteMap.get(t.suite) || { total: 0, passed: 0, failed: 0, skipped: 0, duration: 0 };
    e.total++;
    if (t.status === "passed") e.passed++;
    if (t.status === "failed") e.failed++;
    if (t.status === "skipped") e.skipped++;
    e.duration += t.duration;
    suiteMap.set(t.suite, e);
  }

  // Test list filtering
  let tests: TestResult[] = run.results;
  if (options.includeFailedOnly) tests = tests.filter((t) => t.status === "failed");
  if (!options.includeSkippedTests) tests = tests.filter((t) => t.status !== "skipped");

  // Duration analysis
  const sortedByDuration = [...run.results].sort((a, b) => b.duration - a.duration);
  const top5 = sortedByDuration.slice(0, 5);
  const avgDuration = Math.round(run.results.reduce((s, t) => s + t.duration, 0) / run.results.length);

  const passPercent = (m.passed / m.total) * 100;
  const failPercent = (m.failed / m.total) * 100;

  return (
    <div className={`bg-card border rounded-lg shadow-sm text-sm ${isGray ? "grayscale" : ""}`}>
      {/* Page simulation */}
      <div className="p-6 sm:p-8 space-y-6 max-w-[210mm] mx-auto">

        {/* === HEADER === */}
        <div>
          <div className="flex items-center gap-3">
            <div className="w-10 h-10 rounded-md bg-primary flex items-center justify-center shrink-0">
              <span className="text-primary-foreground font-mono font-bold text-sm">{options.logoText}</span>
            </div>
            <div>
              <h1 className="text-xl font-bold text-foreground">{options.reportTitle}</h1>
              {options.subtitle && <p className="text-xs text-muted-foreground">{options.subtitle}</p>}
            </div>
          </div>

          {(options.organizationName || options.projectName) && (
            <p className="text-xs text-muted-foreground mt-2">
              {[options.organizationName, options.projectName].filter(Boolean).join(" · ")}
            </p>
          )}
          {options.generatedBy && (
            <p className="text-xs text-muted-foreground">Generated by: {options.generatedBy}</p>
          )}

          <div className="h-0.5 bg-primary mt-3" />

          {options.headerNote && (
            <p className="text-xs text-muted-foreground italic mt-3">{options.headerNote}</p>
          )}
        </div>

        {/* === EXECUTIVE SUMMARY === */}
        {options.executiveSummary && (
          <section>
            <SectionHeader title="Executive Summary" />
            <p className="text-xs text-foreground leading-relaxed">{options.executiveSummary}</p>
          </section>
        )}

        {/* === METADATA === */}
        {options.includeMetadata && (
          <section>
            <SectionHeader title="Run Metadata" />
            <div className="grid grid-cols-[auto_1fr] gap-x-4 gap-y-1 text-xs">
              <MetaRow label="Run ID" value={m.runId} />
              <MetaRow label="Timestamp" value={formatDate(m.timestamp)} />
              <MetaRow label="Branch" value={m.branch} />
              <MetaRow label="Environment" value={m.environment} />
              <MetaRow label="Duration" value={formatDuration(m.duration)} />
              {options.customVariables.filter((v) => v.key && v.value).map((v, i) => (
                <MetaRow key={i} label={v.key} value={v.value} />
              ))}
            </div>
          </section>
        )}

        {/* === SUMMARY STATS === */}
        {options.includeSummaryStats && (
          <section>
            <SectionHeader title="Summary" />
            <div className="grid grid-cols-5 gap-2">
              <StatBox label="Total" value={String(m.total)} className="text-foreground" />
              <StatBox label="Passed" value={String(m.passed)} className={statusClass("passed", cm)} />
              <StatBox label="Failed" value={String(m.failed)} className={statusClass("failed", cm)} />
              <StatBox label="Skipped" value={String(m.skipped)} className={statusClass("skipped", cm)} />
              <StatBox label="Pass Rate" value={`${rate}%`} className={rateClass(rate, cm)} />
            </div>
          </section>
        )}

        {/* === PASS/FAIL BAR === */}
        {options.includePassFailBreakdown && (
          <section>
            <div className="flex h-3 rounded-full overflow-hidden">
              <div className="bg-success" style={{ width: `${passPercent}%` }} />
              <div className="bg-destructive" style={{ width: `${failPercent}%` }} />
              <div className="bg-skipped flex-1" />
            </div>
            <div className="flex justify-between text-[10px] mt-1">
              <span className={statusClass("passed", cm)}>{m.passed} passed</span>
              <span className={statusClass("failed", cm)}>{m.failed} failed</span>
              <span className={statusClass("skipped", cm)}>{m.skipped} skipped</span>
            </div>
          </section>
        )}

        {/* === TAG SUMMARY === */}
        {options.includeTagSummary && tagMap.size > 0 && (
          <section>
            <SectionHeader title="Tag Summary" />
            <table className="w-full text-xs">
              <thead>
                <tr className="bg-primary text-primary-foreground">
                  <th className="text-left px-2 py-1.5 font-semibold">Tag</th>
                  <th className="text-center px-2 py-1.5 font-semibold">Total</th>
                  <th className="text-center px-2 py-1.5 font-semibold">Passed</th>
                  <th className="text-center px-2 py-1.5 font-semibold">Failed</th>
                  <th className="text-center px-2 py-1.5 font-semibold">Pass Rate</th>
                </tr>
              </thead>
              <tbody>
                {[...tagMap.entries()].map(([tag, s], i) => (
                  <tr key={tag} className={i % 2 === 1 ? "bg-muted/30" : ""}>
                    <td className="px-2 py-1 font-mono">{tag}</td>
                    <td className="px-2 py-1 text-center">{s.total}</td>
                    <td className="px-2 py-1 text-center">{s.passed}</td>
                    <td className="px-2 py-1 text-center">{s.failed}</td>
                    <td className="px-2 py-1 text-center">{Math.round((s.passed / s.total) * 100)}%</td>
                  </tr>
                ))}
              </tbody>
            </table>
          </section>
        )}

        {/* === SUITE BREAKDOWN === */}
        {options.includeSuiteBreakdown && suiteMap.size > 0 && (
          <section>
            <SectionHeader title="Suite Breakdown" />
            <table className="w-full text-xs">
              <thead>
                <tr className="bg-primary text-primary-foreground">
                  <th className="text-left px-2 py-1.5 font-semibold">Suite</th>
                  <th className="text-center px-2 py-1.5 font-semibold">Total</th>
                  <th className="text-center px-2 py-1.5 font-semibold">Pass</th>
                  <th className="text-center px-2 py-1.5 font-semibold">Fail</th>
                  <th className="text-center px-2 py-1.5 font-semibold">Skip</th>
                  <th className="text-center px-2 py-1.5 font-semibold">Rate</th>
                  <th className="text-right px-2 py-1.5 font-semibold">Avg ms</th>
                </tr>
              </thead>
              <tbody>
                {[...suiteMap.entries()].map(([suite, s], i) => (
                  <tr key={suite} className={i % 2 === 1 ? "bg-muted/30" : ""}>
                    <td className="px-2 py-1 font-mono">{suite}</td>
                    <td className="px-2 py-1 text-center">{s.total}</td>
                    <td className="px-2 py-1 text-center">{s.passed}</td>
                    <td className="px-2 py-1 text-center">{s.failed}</td>
                    <td className="px-2 py-1 text-center">{s.skipped}</td>
                    <td className="px-2 py-1 text-center">{Math.round((s.passed / s.total) * 100)}%</td>
                    <td className="px-2 py-1 text-right">{Math.round(s.duration / s.total)}</td>
                  </tr>
                ))}
              </tbody>
            </table>
          </section>
        )}

        {/* === DURATION ANALYSIS === */}
        {options.includeDurationAnalysis && (
          <section>
            <SectionHeader title="Duration Analysis" />
            <p className="text-xs text-muted-foreground mb-2">
              Average: {avgDuration}ms · Max: {sortedByDuration[0]?.duration || 0}ms · Min: {sortedByDuration[sortedByDuration.length - 1]?.duration || 0}ms
            </p>
            <table className="w-full text-xs">
              <thead>
                <tr className="bg-warning/80 text-warning-foreground">
                  <th className="text-center px-2 py-1.5 font-semibold w-8">#</th>
                  <th className="text-left px-2 py-1.5 font-semibold">Test Name</th>
                  <th className="text-right px-2 py-1.5 font-semibold">Duration</th>
                  <th className="text-center px-2 py-1.5 font-semibold">Status</th>
                </tr>
              </thead>
              <tbody>
                {top5.map((t, i) => (
                  <tr key={t.id} className={i % 2 === 1 ? "bg-muted/30" : ""}>
                    <td className="px-2 py-1 text-center">{i + 1}</td>
                    <td className="px-2 py-1 font-mono truncate max-w-[200px]">{t.name}</td>
                    <td className="px-2 py-1 text-right">{t.duration}ms</td>
                    <td className={`px-2 py-1 text-center font-semibold ${statusClass(t.status, cm)}`}>{t.status.toUpperCase()}</td>
                  </tr>
                ))}
              </tbody>
            </table>
          </section>
        )}

        {/* === TEST LIST === */}
        {options.includeTestList && (
          <section>
            <SectionHeader title={`${options.includeFailedOnly ? "Failed Tests" : "Test Results"} (${tests.length})`} />
            <table className="w-full text-xs">
              <thead>
                <tr className="bg-primary text-primary-foreground">
                  <th className="text-center px-2 py-1.5 font-semibold w-16">Status</th>
                  <th className="text-left px-2 py-1.5 font-semibold">Test Name</th>
                  <th className="text-right px-2 py-1.5 font-semibold w-16">Duration</th>
                  <th className="text-center px-2 py-1.5 font-semibold w-12">Retries</th>
                </tr>
              </thead>
              <tbody>
                {tests.map((t, i) => (
                  <tr key={t.id}>
                    <td className={`px-2 py-1 text-center font-semibold ${statusClass(t.status, cm)} ${i % 2 === 1 ? "bg-muted/30" : ""}`}>
                      {t.status.toUpperCase()}
                    </td>
                    <td className={`px-2 py-1 font-mono ${i % 2 === 1 ? "bg-muted/30" : ""}`}>
                      <div className="truncate max-w-[280px]">{t.name}</div>
                      {options.includeErrorDetails && t.error && (
                        <div className="text-destructive/70 text-[10px] italic mt-0.5 truncate">ERROR: {t.error.split("\n")[0]}</div>
                      )}
                      {options.includeLogs && t.logs && t.logs.length > 0 && (
                        <div className="text-muted-foreground text-[10px] italic mt-0.5 truncate">LOGS: {t.logs.join(" | ")}</div>
                      )}
                    </td>
                    <td className={`px-2 py-1 text-right ${i % 2 === 1 ? "bg-muted/30" : ""}`}>{t.duration}ms</td>
                    <td className={`px-2 py-1 text-center ${i % 2 === 1 ? "bg-muted/30" : ""}`}>{t.retries > 0 ? t.retries : "-"}</td>
                  </tr>
                ))}
              </tbody>
            </table>
          </section>
        )}

        {/* === FOOTER === */}
        <div className="border-t pt-3 flex justify-between text-[10px] text-muted-foreground">
          {options.footerNote && <span>{options.footerNote}</span>}
          <span>Generated {new Date().toLocaleDateString()}</span>
        </div>
      </div>
    </div>
  );
}

function SectionHeader({ title }: { title: string }) {
  return (
    <div className="mb-3">
      <h2 className="text-sm font-bold text-foreground">{title}</h2>
      <div className="h-0.5 bg-primary/50 mt-1" />
    </div>
  );
}

function MetaRow({ label, value }: { label: string; value: string }) {
  return (
    <>
      <span className="font-semibold text-muted-foreground">{label}</span>
      <span className="font-mono text-foreground">{value}</span>
    </>
  );
}

function StatBox({ label, value, className }: { label: string; value: string; className: string }) {
  return (
    <div className="rounded-md bg-muted/40 p-2 text-center">
      <p className="text-[10px] text-muted-foreground uppercase tracking-wider">{label}</p>
      <p className={`text-lg font-bold font-mono ${className}`}>{value}</p>
    </div>
  );
}
