import { SuiteExportOptions } from "@/models/suiteExportTypes";
import { SuiteReportData } from "@/services/suiteReportData";
import { formatDate } from "@/utils/format";
import { TestResult } from "@/models/types";

interface Props {
  data: SuiteReportData;
  options: SuiteExportOptions;
}

function statusClass(status: string, cm: string) {
  if (cm === "grayscale") return "text-foreground";
  if (status === "passed") return "text-success";
  if (status === "failed") return "text-destructive";
  return "text-muted-foreground";
}

function rateClass(rate: number, cm: string) {
  if (cm === "grayscale") return "text-foreground";
  if (rate >= 95) return "text-success";
  if (rate >= 80) return "text-warning";
  return "text-destructive";
}

export function SuiteReportPreview({ data, options }: Props) {
  const cm = options.colorMode;
  const isGray = cm === "grayscale";
  const displayName = options.metadataOverrides.suiteName || data.suiteName;

  // Filter test list
  let tests: TestResult[] = data.latestResults;
  if (options.includeFailedOnly) tests = tests.filter((t) => t.status === "failed");
  if (!options.includeSkippedTests) tests = tests.filter((t) => t.status !== "skipped");

  return (
    <div className={`bg-card border rounded-lg shadow-sm text-sm ${isGray ? "grayscale" : ""}`}>
      <div className="p-6 sm:p-8 space-y-6 max-w-[210mm] mx-auto">

        {/* === HEADER === */}
        <div>
          <div className="flex items-center gap-3">
            <div className="w-10 h-10 rounded-md bg-primary flex items-center justify-center shrink-0">
              <span className="text-primary-foreground font-mono font-bold text-sm">{options.logoText}</span>
            </div>
            <div>
              <h1 className="text-xl font-bold text-foreground">{options.reportTitle}</h1>
              {options.subtitle && <p className="text-xs text-muted-foreground">{options.subtitle}</p>}
            </div>
          </div>
          {(options.organizationName || options.projectName) && (
            <p className="text-xs text-muted-foreground mt-2">
              {[options.organizationName, options.projectName].filter(Boolean).join(" · ")}
            </p>
          )}
          {options.generatedBy && <p className="text-xs text-muted-foreground">Generated by: {options.generatedBy}</p>}
          <div className="h-0.5 bg-primary mt-3" />
          {options.headerNote && <p className="text-xs text-muted-foreground italic mt-3">{options.headerNote}</p>}
        </div>

        {/* === EXECUTIVE SUMMARY === */}
        {options.executiveSummary && (
          <section>
            <SectionHeader title="Executive Summary" />
            <p className="text-xs text-foreground leading-relaxed">{options.executiveSummary}</p>
          </section>
        )}

        {/* === SUITE METADATA === */}
        {options.includeMetadata && (
          <section>
            <SectionHeader title="Suite Overview" />
            <div className="grid grid-cols-[auto_1fr] gap-x-4 gap-y-1 text-xs">
              <MetaRow label="Suite Name" value={displayName} />
              <MetaRow label="First Seen" value={formatDate(data.firstSeen)} />
              <MetaRow label="Last Seen" value={formatDate(data.lastSeen)} />
              <MetaRow label="Runs Analyzed" value={`${data.runsAnalyzed} of ${data.totalRuns} total`} />
              {options.metadataOverrides.environment && <MetaRow label="Environment" value={options.metadataOverrides.environment} />}
              {options.customVariables.filter((v) => v.key && v.value).map((v, i) => (
                <MetaRow key={i} label={v.key} value={v.value} />
              ))}
            </div>
          </section>
        )}

        {/* === STABILITY OVERVIEW === */}
        {options.includeStabilityOverview && (
          <section>
            <SectionHeader title="Stability Overview" />
            <div className="grid grid-cols-4 gap-2">
              <StatBox label="Stability" value={`${data.stabilityScore}%`} className={rateClass(data.stabilityScore, cm)} />
              <StatBox label="Avg Pass Rate" value={`${data.avgPassRate}%`} className={rateClass(data.avgPassRate, cm)} />
              <StatBox label="Perfect Runs" value={`${data.perfectRuns}/${data.runsAnalyzed}`} className="text-foreground" />
              <StatBox label="Trend" value={`${data.trend >= 0 ? "+" : ""}${data.trend}%`} className={data.trend >= 0 ? (isGray ? "text-foreground" : "text-success") : (isGray ? "text-foreground" : "text-destructive")} />
            </div>
            {/* Visual stability bar */}
            <div className="mt-3">
              <div className="flex gap-0.5">
                {data.history.map((h, i) => (
                  <div
                    key={i}
                    className={`h-4 flex-1 rounded-sm ${h.passRate === 100 ? "bg-success" : h.passRate >= 80 ? "bg-warning" : "bg-destructive"}`}
                    title={`${new Date(h.timestamp).toLocaleDateString()} — ${h.passRate}%`}
                  />
                ))}
              </div>
              <div className="flex justify-between text-[9px] text-muted-foreground mt-1">
                <span>{data.history.length > 0 ? new Date(data.history[0].timestamp).toLocaleDateString("en-US", { month: "short", day: "numeric" }) : ""}</span>
                <span className="text-[9px]">Each block = 1 run (🟢 100% · 🟡 80%+ · 🔴 &lt;80%)</span>
                <span>{data.history.length > 0 ? new Date(data.history[data.history.length - 1].timestamp).toLocaleDateString("en-US", { month: "short", day: "numeric" }) : ""}</span>
              </div>
            </div>
          </section>
        )}

        {/* === PASS RATE TREND === */}
        {options.includePassRateTrend && data.history.length > 1 && (
          <section>
            <SectionHeader title="Pass Rate Trend" />
            <table className="w-full text-xs">
              <thead>
                <tr className="bg-primary text-primary-foreground">
                  <th className="text-left px-2 py-1.5 font-semibold">Run</th>
                  <th className="text-center px-2 py-1.5 font-semibold">Date</th>
                  <th className="text-center px-2 py-1.5 font-semibold">Tests</th>
                  <th className="text-center px-2 py-1.5 font-semibold">✓</th>
                  <th className="text-center px-2 py-1.5 font-semibold">✗</th>
                  <th className="text-center px-2 py-1.5 font-semibold">Rate</th>
                  <th className="text-right px-2 py-1.5 font-semibold">Duration</th>
                </tr>
              </thead>
              <tbody>
                {[...data.history].reverse().slice(0, 10).map((h, i) => (
                  <tr key={h.runId} className={i % 2 === 1 ? "bg-muted/30" : ""}>
                    <td className="px-2 py-1 font-mono truncate max-w-[120px]">{h.runId.slice(0, 16)}</td>
                    <td className="px-2 py-1 text-center">{new Date(h.timestamp).toLocaleDateString("en-US", { month: "short", day: "numeric" })}</td>
                    <td className="px-2 py-1 text-center">{h.total}</td>
                    <td className={`px-2 py-1 text-center ${statusClass("passed", cm)}`}>{h.passed}</td>
                    <td className={`px-2 py-1 text-center ${statusClass("failed", cm)}`}>{h.failed}</td>
                    <td className={`px-2 py-1 text-center font-bold ${rateClass(h.passRate, cm)}`}>{h.passRate}%</td>
                    <td className="px-2 py-1 text-right">{Math.round(h.duration / 1000)}s</td>
                  </tr>
                ))}
              </tbody>
            </table>
            {data.history.length > 10 && (
              <p className="text-[10px] text-muted-foreground mt-1 text-center">Showing last 10 of {data.history.length} runs</p>
            )}
          </section>
        )}

        {/* === CROSS-RUN COMPARISON === */}
        {options.includeCrossRunComparison && data.history.length > 1 && (
          <section>
            <SectionHeader title="Cross-Run Test Comparison" />
            <p className="text-[10px] text-muted-foreground mb-2">Status of each test across the last {Math.min(data.history.length, 5)} runs</p>
            <CrossRunTable data={data} cm={cm} />
          </section>
        )}

        {/* === FLAKY TESTS === */}
        {options.includeFlakyTests && data.flakyTests.length > 0 && (
          <section>
            <SectionHeader title={`Flaky Tests (${data.flakyTests.length})`} />
            <p className="text-[10px] text-muted-foreground mb-2">Tests that flip between pass and fail across runs</p>
            <table className="w-full text-xs">
              <thead>
                <tr className="bg-warning/80 text-warning-foreground">
                  <th className="text-left px-2 py-1.5 font-semibold">Test Name</th>
                  <th className="text-center px-2 py-1.5 font-semibold">Runs</th>
                  <th className="text-center px-2 py-1.5 font-semibold">✓</th>
                  <th className="text-center px-2 py-1.5 font-semibold">✗</th>
                  <th className="text-center px-2 py-1.5 font-semibold">Flake Rate</th>
                  <th className="text-center px-2 py-1.5 font-semibold">Last</th>
                </tr>
              </thead>
              <tbody>
                {data.flakyTests.map((t, i) => (
                  <tr key={t.name} className={i % 2 === 1 ? "bg-muted/30" : ""}>
                    <td className="px-2 py-1 font-mono truncate max-w-[200px]">{t.name}</td>
                    <td className="px-2 py-1 text-center">{t.totalRuns}</td>
                    <td className={`px-2 py-1 text-center ${statusClass("passed", cm)}`}>{t.passed}</td>
                    <td className={`px-2 py-1 text-center ${statusClass("failed", cm)}`}>{t.failed}</td>
                    <td className="px-2 py-1 text-center font-bold text-warning">{t.flakeRate}%</td>
                    <td className={`px-2 py-1 text-center font-semibold ${statusClass(t.lastStatus, cm)}`}>{t.lastStatus.toUpperCase()}</td>
                  </tr>
                ))}
              </tbody>
            </table>
          </section>
        )}

        {/* === FAILURE PATTERNS === */}
        {options.includeFailurePatterns && data.failurePatterns.length > 0 && (
          <section>
            <SectionHeader title="Failure Patterns" />
            <p className="text-[10px] text-muted-foreground mb-2">Recurring failure categories across all runs</p>
            <div className="space-y-2">
              {data.failurePatterns.map((p) => (
                <div key={p.category} className="rounded border p-2.5">
                  <div className="flex items-center justify-between">
                    <span className="text-xs font-semibold text-foreground">{p.category}</span>
                    <span className="text-xs font-mono text-muted-foreground">{p.count} occurrences ({p.percentage}%)</span>
                  </div>
                  {/* Bar */}
                  <div className="h-1.5 bg-muted rounded-full mt-1.5 overflow-hidden">
                    <div className="h-full bg-destructive rounded-full" style={{ width: `${p.percentage}%` }} />
                  </div>
                  {p.sampleError && (
                    <p className="text-[10px] text-muted-foreground mt-1 font-mono truncate">
                      Sample: {p.sampleError}
                    </p>
                  )}
                  <p className="text-[10px] text-muted-foreground mt-0.5">
                    Affects: {p.affectedTests.slice(0, 3).join(", ")}{p.affectedTests.length > 3 ? ` +${p.affectedTests.length - 3} more` : ""}
                  </p>
                </div>
              ))}
            </div>
          </section>
        )}

        {/* === TAG SUMMARY === */}
        {options.includeTagSummary && data.tagMap.size > 0 && (
          <section>
            <SectionHeader title="Tag Summary (Latest Run)" />
            <table className="w-full text-xs">
              <thead>
                <tr className="bg-primary text-primary-foreground">
                  <th className="text-left px-2 py-1.5 font-semibold">Tag</th>
                  <th className="text-center px-2 py-1.5 font-semibold">Total</th>
                  <th className="text-center px-2 py-1.5 font-semibold">Passed</th>
                  <th className="text-center px-2 py-1.5 font-semibold">Failed</th>
                  <th className="text-center px-2 py-1.5 font-semibold">Pass Rate</th>
                </tr>
              </thead>
              <tbody>
                {[...data.tagMap.entries()].map(([tag, s], i) => (
                  <tr key={tag} className={i % 2 === 1 ? "bg-muted/30" : ""}>
                    <td className="px-2 py-1 font-mono">{tag}</td>
                    <td className="px-2 py-1 text-center">{s.total}</td>
                    <td className="px-2 py-1 text-center">{s.passed}</td>
                    <td className="px-2 py-1 text-center">{s.failed}</td>
                    <td className="px-2 py-1 text-center">{Math.round((s.passed / s.total) * 100)}%</td>
                  </tr>
                ))}
              </tbody>
            </table>
          </section>
        )}

        {/* === DURATION ANALYSIS === */}
        {options.includeDurationAnalysis && data.latestResults.length > 0 && (
          <section>
            <SectionHeader title="Duration Analysis (Latest Run)" />
            {(() => {
              const sorted = [...data.latestResults].sort((a, b) => b.duration - a.duration);
              const avg = Math.round(sorted.reduce((s, t) => s + t.duration, 0) / sorted.length);
              return (
                <>
                  <p className="text-xs text-muted-foreground mb-2">
                    Average: {avg}ms · Max: {sorted[0]?.duration || 0}ms · Min: {sorted[sorted.length - 1]?.duration || 0}ms
                  </p>
                  <table className="w-full text-xs">
                    <thead>
                      <tr className="bg-warning/80 text-warning-foreground">
                        <th className="text-center px-2 py-1.5 font-semibold w-8">#</th>
                        <th className="text-left px-2 py-1.5 font-semibold">Test</th>
                        <th className="text-right px-2 py-1.5 font-semibold">Duration</th>
                        <th className="text-center px-2 py-1.5 font-semibold">Status</th>
                      </tr>
                    </thead>
                    <tbody>
                      {sorted.slice(0, 5).map((t, i) => (
                        <tr key={t.id} className={i % 2 === 1 ? "bg-muted/30" : ""}>
                          <td className="px-2 py-1 text-center">{i + 1}</td>
                          <td className="px-2 py-1 font-mono truncate max-w-[200px]">{t.name}</td>
                          <td className="px-2 py-1 text-right">{t.duration}ms</td>
                          <td className={`px-2 py-1 text-center font-semibold ${statusClass(t.status, cm)}`}>{t.status.toUpperCase()}</td>
                        </tr>
                      ))}
                    </tbody>
                  </table>
                </>
              );
            })()}
          </section>
        )}

        {/* === TEST LIST === */}
        {options.includeTestList && (
          <section>
            <SectionHeader title={`${options.includeFailedOnly ? "Failed Tests" : "Test Results"} — Latest Run (${tests.length})`} />
            <table className="w-full text-xs">
              <thead>
                <tr className="bg-primary text-primary-foreground">
                  <th className="text-center px-2 py-1.5 font-semibold w-16">Status</th>
                  <th className="text-left px-2 py-1.5 font-semibold">Test Name</th>
                  <th className="text-right px-2 py-1.5 font-semibold w-16">Duration</th>
                  <th className="text-center px-2 py-1.5 font-semibold w-12">Retries</th>
                </tr>
              </thead>
              <tbody>
                {tests.map((t, i) => (
                  <tr key={t.id}>
                    <td className={`px-2 py-1 text-center font-semibold ${statusClass(t.status, cm)} ${i % 2 === 1 ? "bg-muted/30" : ""}`}>
                      {t.status.toUpperCase()}
                    </td>
                    <td className={`px-2 py-1 font-mono ${i % 2 === 1 ? "bg-muted/30" : ""}`}>
                      <div className="truncate max-w-[280px]">{t.name}</div>
                      {options.includeErrorDetails && t.error && (
                        <div className="text-destructive/70 text-[10px] italic mt-0.5 truncate">ERROR: {t.error.split("\n")[0]}</div>
                      )}
                    </td>
                    <td className={`px-2 py-1 text-right ${i % 2 === 1 ? "bg-muted/30" : ""}`}>{t.duration}ms</td>
                    <td className={`px-2 py-1 text-center ${i % 2 === 1 ? "bg-muted/30" : ""}`}>{t.retries > 0 ? t.retries : "-"}</td>
                  </tr>
                ))}
              </tbody>
            </table>
          </section>
        )}

        {/* === FOOTER === */}
        <div className="border-t pt-3 flex justify-between text-[10px] text-muted-foreground">
          {options.footerNote && <span>{options.footerNote}</span>}
          <span>Generated {new Date().toLocaleDateString()}</span>
        </div>
      </div>
    </div>
  );
}

function CrossRunTable({ data, cm }: { data: SuiteReportData; cm: string }) {
  const recentRuns = [...data.history].reverse().slice(0, 5);
  const testNames = [...data.crossRunStatus.keys()].sort();

  return (
    <div className="overflow-x-auto">
      <table className="w-full text-xs">
        <thead>
          <tr className="bg-primary text-primary-foreground">
            <th className="text-left px-2 py-1.5 font-semibold">Test</th>
            {recentRuns.map((h) => (
              <th key={h.runId} className="text-center px-1.5 py-1.5 font-semibold text-[9px]">
                {new Date(h.timestamp).toLocaleDateString("en-US", { month: "short", day: "numeric" })}
              </th>
            ))}
          </tr>
        </thead>
        <tbody>
          {testNames.slice(0, 15).map((name, i) => {
            const runMap = data.crossRunStatus.get(name);
            return (
              <tr key={name} className={i % 2 === 1 ? "bg-muted/30" : ""}>
                <td className="px-2 py-1 font-mono truncate max-w-[160px]">{name}</td>
                {recentRuns.map((h) => {
                  const status = runMap?.get(h.runId);
                  const icon = status === "passed" ? "✓" : status === "failed" ? "✗" : status === "skipped" ? "⊘" : "—";
                  const cls = status ? statusClass(status, cm) : "text-muted-foreground";
                  return (
                    <td key={h.runId} className={`px-1.5 py-1 text-center font-bold ${cls}`}>
                      {icon}
                    </td>
                  );
                })}
              </tr>
            );
          })}
        </tbody>
      </table>
      {testNames.length > 15 && (
        <p className="text-[10px] text-muted-foreground mt-1 text-center">Showing 15 of {testNames.length} tests</p>
      )}
    </div>
  );
}

function SectionHeader({ title }: { title: string }) {
  return (
    <div className="mb-3">
      <h2 className="text-sm font-bold text-foreground">{title}</h2>
      <div className="h-0.5 bg-primary/50 mt-1" />
    </div>
  );
}

function MetaRow({ label, value }: { label: string; value: string }) {
  return (
    <>
      <span className="font-semibold text-muted-foreground">{label}</span>
      <span className="font-mono text-foreground">{value}</span>
    </>
  );
}

function StatBox({ label, value, className }: { label: string; value: string; className: string }) {
  return (
    <div className="rounded-md bg-muted/40 p-2 text-center">
      <p className="text-[10px] text-muted-foreground uppercase tracking-wider">{label}</p>
      <p className={`text-lg font-bold font-mono ${className}`}>{value}</p>
    </div>
  );
}
