import { TestExportOptions } from "@/models/testExportTypes";
import { Input } from "@/components/ui/input";
import { Switch } from "@/components/ui/switch";
import { Button } from "@/components/ui/button";
import { Textarea } from "@/components/ui/textarea";

interface Props {
  options: TestExportOptions;
  onChange: (options: TestExportOptions) => void;
}

export function TestExportSettingsPanel({ options, onChange }: Props) {
  const update = <K extends keyof TestExportOptions>(key: K, value: TestExportOptions[K]) =>
    onChange({ ...options, [key]: value });

  const addCustomVar = () =>
    update("customVariables", [...options.customVariables, { key: "", value: "" }]);

  const updateCustomVar = (index: number, field: "key" | "value", val: string) => {
    const vars = [...options.customVariables];
    vars[index] = { ...vars[index], [field]: val };
    update("customVariables", vars);
  };

  const removeCustomVar = (index: number) =>
    update("customVariables", options.customVariables.filter((_, i) => i !== index));

  return (
    <div className="space-y-5">
      <Section title="Report Identity">
        <Field label="File Name"><Input value={options.fileName} onChange={e => update("fileName", e.target.value)} className="font-mono text-xs h-8" /></Field>
        <Field label="Report Title"><Input value={options.reportTitle} onChange={e => update("reportTitle", e.target.value)} className="font-mono text-xs h-8" /></Field>
        <Field label="Subtitle"><Input value={options.subtitle} onChange={e => update("subtitle", e.target.value)} className="font-mono text-xs h-8" /></Field>
        <Field label="Organization"><Input value={options.organizationName} onChange={e => update("organizationName", e.target.value)} className="font-mono text-xs h-8" /></Field>
        <Field label="Project"><Input value={options.projectName} onChange={e => update("projectName", e.target.value)} className="font-mono text-xs h-8" /></Field>
        <Field label="Generated By"><Input value={options.generatedBy} onChange={e => update("generatedBy", e.target.value)} className="font-mono text-xs h-8" /></Field>
        <Field label="Logo Text (2 chars)"><Input value={options.logoText} maxLength={2} onChange={e => update("logoText", e.target.value)} className="font-mono text-xs h-8 w-16" /></Field>
      </Section>

      <Section title="Notes & Commentary">
        <Field label="Header Note"><Textarea value={options.headerNote} onChange={e => update("headerNote", e.target.value)} className="font-mono text-xs min-h-[60px]" /></Field>
        <Field label="Executive Summary"><Textarea value={options.executiveSummary} onChange={e => update("executiveSummary", e.target.value)} className="font-mono text-xs min-h-[60px]" /></Field>
        <Field label="Footer Note"><Input value={options.footerNote} onChange={e => update("footerNote", e.target.value)} className="font-mono text-xs h-8" /></Field>
      </Section>

      <Section title="Custom Variables" action={<Button variant="ghost" size="sm" className="h-7 text-xs font-mono" onClick={addCustomVar}>+ Add</Button>}>
        {options.customVariables.map((v, i) => (
          <div key={i} className="flex gap-1.5 items-center">
            <Input placeholder="Key" value={v.key} onChange={e => updateCustomVar(i, "key", e.target.value)} className="font-mono text-xs h-7 flex-1" />
            <Input placeholder="Value" value={v.value} onChange={e => updateCustomVar(i, "value", e.target.value)} className="font-mono text-xs h-7 flex-1" />
            <Button variant="ghost" size="sm" className="h-7 w-7 p-0 text-xs text-destructive" onClick={() => removeCustomVar(i)}>×</Button>
          </div>
        ))}
      </Section>

      <Section title="Sections">
        <SwitchField label="Health Summary" checked={options.includeHealthSummary} onChange={v => update("includeHealthSummary", v)} />
        <SwitchField label="Status Timeline" checked={options.includeStatusTimeline} onChange={v => update("includeStatusTimeline", v)} />
        <SwitchField label="Failure Cause Analysis" checked={options.includeFailureCauseAnalysis} onChange={v => update("includeFailureCauseAnalysis", v)} />
        <SwitchField label="Duration Trend" checked={options.includeDurationTrend} onChange={v => update("includeDurationTrend", v)} />
        <SwitchField label="Retry Analysis" checked={options.includeRetryAnalysis} onChange={v => update("includeRetryAnalysis", v)} />
        <SwitchField label="Run History" checked={options.includeRunHistory} onChange={v => update("includeRunHistory", v)} />
        <SwitchField label="Tags & Metadata" checked={options.includeTagsAndMetadata} onChange={v => update("includeTagsAndMetadata", v)} />
        <SwitchField label="Error Details in Failure Analysis" checked={options.includeErrorDetails} onChange={v => update("includeErrorDetails", v)} />
      </Section>

      <Section title="Formatting">
        <Field label="Page Size">
          <div className="flex gap-1.5">
            {(["a4", "letter"] as const).map(s => (
              <Button key={s} variant={options.pageSize === s ? "default" : "outline"} size="sm" className="h-7 text-xs font-mono flex-1" onClick={() => update("pageSize", s)}>{s.toUpperCase()}</Button>
            ))}
          </div>
        </Field>
        <Field label="Color Mode">
          <div className="flex gap-1.5">
            {(["color", "grayscale"] as const).map(m => (
              <Button key={m} variant={options.colorMode === m ? "default" : "outline"} size="sm" className="h-7 text-xs font-mono flex-1" onClick={() => update("colorMode", m)}>{m.charAt(0).toUpperCase() + m.slice(1)}</Button>
            ))}
          </div>
        </Field>
      </Section>
    </div>
  );
}

function Section({ title, children, action }: { title: string; children: React.ReactNode; action?: React.ReactNode }) {
  return (
    <div className="space-y-2.5">
      <div className="flex items-center justify-between">
        <h3 className="text-xs font-medium text-muted-foreground uppercase tracking-wider">{title}</h3>
        {action}
      </div>
      {children}
    </div>
  );
}

function Field({ label, children }: { label: string; children: React.ReactNode }) {
  return (
    <div className="space-y-1">
      <label className="text-xs text-muted-foreground">{label}</label>
      {children}
    </div>
  );
}

function SwitchField({ label, checked, onChange }: { label: string; checked: boolean; onChange: (v: boolean) => void }) {
  return (
    <div className="flex items-center justify-between py-1">
      <span className="text-xs text-foreground">{label}</span>
      <Switch checked={checked} onCheckedChange={onChange} />
    </div>
  );
}
